@startuml

package contract {
  class Contract {
    - contractId: Long
    - status: ContractStatus
    - validThrough: DateRange
    - changeLogs: Contract[]
  }
}

package pricingplan {
  class PricingPlan {
    - pricingPlanId: Long
    - contractId: Long
    - bin: Set<DistanceRangePricingElement>
  }

  class DistanceRangePricingElement <<value>> {
    - from: Distance 'not inclusive
    - to: Distance 'inclusive
    - step: Distance
    - pricePerStep: Money
  }
}

Contract -> PricingPlan
PricingPlan o-- DistanceRangePricingElement

@enduml